### ISSUE TITLE
what is the meaning of "requires proprietary plugin"

### ISSUE THREAD

**Issue by CyrusNG** [mnbf9rca/cups-google-print#2]
I want to connect HP LaserJet Professional m1132 MFP printer, but fail. And I find model shows "HP LaserJet Professional m1132 MFP, hpcups 3.14.3, requires proprietary plugin".
what is the meaning of "requires proprietary plugin", it means I need install manually the hp plugin at this docker? or I need install hp plugin on my mac that connect to CUPS server? or others? Thanks.

**Comment by mnbf9rca** [comment]
i think the former - i removed proprietary plugins from teh container. Feel free to suggest a change via a pull request.
